### ISSUE TITLE
[Bug]: VMware tools latest version not reported

### ISSUE THREAD

**Issue by JonathanPitre** [aaronparker/evergreen#336]
### What happened?

According to the VMware tools release notes, the latest version is **12.0.5-19716617** and yet Evergreen reports version 12.0.0-19345655.

![image](https://user-images.githubusercontent.com/15003329/171068508-fde48ce0-a43b-4187-a6a6-7ff23d88857d.png)
![image](https://user-images.githubusercontent.com/15003329/171068523-3c3d7c89-e972-4076-89cc-84ba7a36eba9.png)

### Version

2205.567

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
VERBOSE: Get-EvergreenApp: Function exists: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2205.567\Apps\Get-vmwaretools.ps1.
VERBOSE: Get-EvergreenApp: Dot sourcing: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2205.567\Apps\Get-vmwaretools.ps1.
VERBOSE: Get-FunctionResource: read application resource strings from [C:\Program Files\WindowsPowerShell\Modules\Evergreen\2205.567\Manifests\vmwaretools.json]
VERBOSE: Get-EvergreenApp: Calling: Get-vmwaretools.
VERBOSE: Invoke-WebRequestWrapper: Adding ContentType.
VERBOSE: Invoke-WebRequestWrapper: Using temp file C:\Users\Jon\AppData\Local\Temp\tmpF279.tmp.
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [UserAgent: Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) AppleWebKit/534.6 (KHTML, like Gecko) Chrome/7.0.500.0
Safari/534.6].
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [ContentType: text/plain].
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [UseBasicParsing: True].
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [Method: Default].
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [Uri: https://packages.vmware.com/tools/versions].
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [PassThru: True].
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [OutFile: C:\Users\Jon\AppData\Local\Temp\tmpF279.tmp].
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [ErrorAction: Continue].
VERBOSE: GET with 0-byte payload
VERBOSE: received 10445-byte response of content type text/plain
VERBOSE: Invoke-WebRequestWrapper: Response: [200].
VERBOSE: Invoke-WebRequestWrapper: Content type: [text/plain].
VERBOSE: Invoke-WebRequestWrapper: Returning content of length: [175].
VERBOSE: Get-VMwareTools: Filtering version table with 175 lines.
VERBOSE: Get-VMwareTools: Filtered to 144 lines.
VERBOSE: Get-VMwareTools: Selecting first 20 lines.
VERBOSE: Get-VMwareTools: Convert to table.
VERBOSE: Get-VMwareTools: Found version: 12.0.0-19345655
VERBOSE: Get-EvergreenApp: Output result from: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2205.567\Apps\Get-vmwaretools.ps1.

Version Architecture URI
------- ------------ ---
12.0.0  x64          https://packages.vmware.com/tools/releases/latest/windows/x64/VMware-tools-12.0.0-19345655-x86_64.exe
12.0.0  x86          https://packages.vmware.com/tools/releases/latest/windows/x86/VMware-tools-12.0.0-19345655-i386.exe
```

**Comment by aaronparker** [comment]
The challenge with the source used to determine the Tools version, is that it doesn't provide a consistent data source. Listed below is what the source is showing right now.

The function has to convert the text to a table to be able to support it, so when column 3 is missing, this will break the conversion, thus lines with `esx/0.0` are filtered out of the sort.

```text
# Column 1: Tools version on NGC/VI Client
# Column 2: ESXi server version.'esx/0.0' indicates that the tools version
# is not yet bundled with ESXi.
# Column 3: ESXi server build number
# Column 4: Tools version on guest Setup/About page
# Column 5: Tools build number
#
12293       esx/0.0                                 12.0.5          19716617
12288       esx/6.5p08          19588618            12.0.0          19345655
11365       esx/7.0p04          19482537            11.3.5          18557794
12288       esx/0.0                                 12.0.0          19345655
11365       esx/6.7p06          18828794            11.3.5          18557794
10360       esx/0.0                                 10.3.24         18733423
```

**Comment by JonathanPitre** [comment]
It got worst, now it won't even download the binaries with the provided URLs.

**Comment by aaronparker** [comment]
Fix released in `2207.592`

**Comment by JonathanPitre** [comment]
It still won't report the latest version. 
https://docs.vmware.com/en/VMware-Tools/12.0/rn/VMware-Tools-1205-Release-Notes.html

`get-evergreenapp vmwaretools -verbose
VERBOSE: Get-EvergreenApp: Function exists: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2207.592\Apps\Get-vmwaretools.ps1.
VERBOSE: Get-EvergreenApp: Dot sourcing: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2207.592\Apps\Get-vmwaretools.ps1.
VERBOSE: Get-FunctionResource: read application resource strings from [C:\Program Files\WindowsPowerShell\Modules\Evergreen\2207.592\Manifests\vmwaretools.json]
VERBOSE: Get-EvergreenApp: Calling: Get-vmwaretools.
VERBOSE: Invoke-WebRequestWrapper: Adding ContentType.
VERBOSE: Invoke-WebRequestWrapper: Using temp file C:\Users\Jon\AppData\Local\Temp\tmpD9A8.tmp.
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [UserAgent: Mozilla/5.0 (Windows NT; Windows NT 10.0; en-US) AppleWebKit/534.6 (KHTML, like Gecko) Chrome/7.0.500.0
Safari/534.6].
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [ContentType: text/plain].
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [UseBasicParsing: True].
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [Method: Default].
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [Uri: https://packages.vmware.com/tools/versions].
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [PassThru: True].
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [OutFile: C:\Users\Jon\AppData\Local\Temp\tmpD9A8.tmp].
VERBOSE: GET with 0-byte payload
VERBOSE: received 10522-byte response of content type text/plain
VERBOSE: Invoke-WebRequestWrapper: Response: [200].
VERBOSE: Invoke-WebRequestWrapper: Content type: [text/plain].
VERBOSE: Invoke-WebRequestWrapper: Returning content of length: [176].
VERBOSE: Get-VMwareTools: Filtering version table with 176 lines.
VERBOSE: Get-VMwareTools: Filtered to 145 lines.
VERBOSE: Get-VMwareTools: Selecting first 20 lines.
VERBOSE: Get-VMwareTools: Convert to table.
VERBOSE: Get-VMwareTools: Found version: 12.0.0-19345655
VERBOSE: Get-EvergreenApp: Output result from: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2207.592\Apps\Get-vmwaretools.ps1.

Version Architecture URI
------- ------------ ---
12.0.0  x64          https://packages.vmware.com/tools/releases/12.0.0/windows/x64/VMware-tools-12.0.0-19345655-x86_64.exe
12.0.0  x86          https://packages.vmware.com/tools/releases/12.0.0/windows/x86/VMware-tools-12.0.0-19345655-i386.exe`
